(in-package :cl-user)

(defpackage :cl-tuples
  (:use :cl :alexandria :iterate)
  (:nicknames :tuples)
  (:export aabb
           aabb*
           aabb-aref
           aabb-aref*
           aabb-aref-setter
           aabb-aref-setter*
           aabb-array
           aabb-array-dimensions
           aabb-fill-pointer
           aabb-key-values
           aabb-map*
           aabb-reduce*
           aabb-setter*
           aabb-values*
           aabb-vector-push
           aabb-vector-push*
           aabb-vector-push-extend
           aabb-vector-push-extend*
           angle-axis
           angle-axis*
           angle-axis-aref
           angle-axis-aref*
           angle-axis-aref-setter
           angle-axis-aref-setter*
           angle-axis-array
           angle-axis-array-dimensions
           angle-axis-fill-pointer
           angle-axis-key-values
           angle-axis-map*
           angle-axis-matrix33*
           angle-axis-quaternion*
           angle-axis-reduce*
           angle-axis-setter*
           angle-axis-values*
           angle-axis-vector-push
           angle-axis-vector-push*
           angle-axis-vector-push-extend
           angle-axis-vector-push-extend*
           cofactor-matrix22*
           cofactor-matrix33*
           cofactor-matrix44*
           colour
           colour*
           colour-aref
           colour-aref*
           colour-aref-setter
           colour-aref-setter*
           colour-array
           colour-array-dimensions
           colour-fill-pointer
           colour-key-values
           colour-map*
           colour-reduce*
           colour-setter*
           colour-values*
           colour-vector-push
           colour-vector-push*
           colour-vector-push-extend
           colour-vector-push-extend*
           def-tuple-op
           def-tuple-type
           delta-vector3d*
           disable-tuples-syntax
           enable-tuples-syntax
           fast-float
           fast-pi
           file-enable-tuples-syntax
           *float-print-format*
           height
           identity-matrix44*
           inverted-matrix22*
           inverted-matrix33*
           inverted-matrix44*
           locally-disable-tuples-syntax
           locally-enable-tuples-syntax
           make-aabb
           make-aabb*
           make-aabb-array
           make-angle-axis
           make-angle-axis*
           make-angle-axis-array
           make-colour
           make-colour*
           make-colour-array
           make-matrix22
           make-matrix22*
           make-matrix22-array
           make-matrix33
           make-matrix33*
           make-matrix33-array
           make-matrix44
           make-matrix44*
           make-matrix44-array
           make-quaternion
           make-quaternion*
           make-quaternion-array
           make-rect
           make-rect*
           make-rect-array
           make-triangle
           make-triangle*
           make-triangle-array
           make-tuple-symbol
           make-vector2d
           make-vector2d*
           make-vector2d-array
           make-vector3d
           make-vector3d*
           make-vector3d-array
           make-vertex3d
           make-vertex3d*
           make-vertex3d-array
           matrix22
           matrix22*
           matrix22-aref
           matrix22-aref*
           matrix22-aref-setter
           matrix22-aref-setter*
           matrix22-array
           matrix22-array-dimensions
           matrix22-determinant*
           matrix22-fill-pointer
           matrix22-key-values
           matrix22-map*
           matrix22-reduce*
           matrix22-scale*
           matrix22-setter*
           matrix22-values*
           matrix22-vector-push
           matrix22-vector-push*
           matrix22-vector-push-extend
           matrix22-vector-push-extend*
           matrix33
           matrix33*
           matrix33-aref
           matrix33-aref*
           matrix33-aref-setter
           matrix33-aref-setter*
           matrix33-array
           matrix33-array-dimensions
           matrix33-determinant*
           matrix33-fill-pointer
           matrix33-key-values
           matrix33-map*
           matrix33-matrix44*
           matrix33-product*
           matrix33-reduce*
           matrix33-scale*
           matrix33-setter*
           matrix33-values*
           matrix33-vector-push
           matrix33-vector-push*
           matrix33-vector-push-extend
           matrix33-vector-push-extend*
           matrix44
           matrix44*
           matrix44-aref
           matrix44-aref*
           matrix44-aref-setter
           matrix44-aref-setter*
           matrix44-array
           matrix44-array-dimensions
           matrix44-determinant*
           matrix44-fill-pointer
           matrix44-key-values
           matrix44-map*
           matrix44-matrix33*
           matrix44-product*
           matrix44-reduce*
           matrix44-scale*
           matrix44-setter*
           matrix44-values*
           matrix44-vector-push
           matrix44-vector-push*
           matrix44-vector-push-extend
           matrix44-vector-push-extend*
           new-aabb
           new-angle-axis
           new-colour
           new-matrix22
           new-matrix33
           new-matrix44
           new-quaternion
           new-rect
           new-triangle
           new-vector2d
           new-vector3d
           new-vertex3d
           nth-aabb
           nth-angle-axis
           nth-colour
           nth-matrix22
           nth-matrix33
           nth-matrix44
           nth-quaternion
           nth-rect
           nth-triangle
           nth-vector2d
           nth-vector3d
           nth-vertex3d
           print-matrix22*
           print-matrix33*
           print-matrix44*
           quaternion
           quaternion*
           quaternion-aref
           quaternion-aref*
           quaternion-aref-setter
           quaternion-aref-setter*
           quaternion-array
           quaternion-array-dimensions
           quaternion-conjugate*
           quaternion-dot*
           quaternion-fill-pointer
           quaternion-inverse*
           quaternion-key-values
           quaternion-mag*
           quaternion-mag-square*
           quaternion-map*
           quaternion-matrix33*
           quaternion-normalize*
           quaternion-product*
           quaternion-reduce*
           quaternion-scale*
           quaternion-setter*
           quaternion-sum*
           quaternion-transform-vector3d*
           quaternion-values*
           quaternion-vector-push
           quaternion-vector-push*
           quaternion-vector-push-extend
           quaternion-vector-push-extend*
           rect
           rect*
           rect-aref
           rect-aref*
           rect-aref-setter
           rect-aref-setter*
           rect-array
           rect-array-dimensions
           rect-fill-pointer
           rect-key-values
           rect-map*
           rect-reduce*
           rect-setter*
           rect-values*
           rect-vector-push
           rect-vector-push*
           rect-vector-push-extend
           rect-vector-push-extend*
           restore-tuples-syntax-state
           rotatex-matrix44*
           rotatey-matrix44*
           rotatez-matrix44*
           scaling-matrix44*
           set-aabb
           set-angle-axis
           set-colour
           set-matrix22
           set-matrix33
           set-matrix44
           set-quaternion
           set-rect
           set-triangle
           set-vector2d
           set-vector3d
           set-vertex3d
           transform-vector2d*
           transform-vector3d*
           transform-vertex2d*
           transform-vertex3d*
           translation-matrix44*
           transpose-matrix33*
           transpose-matrix44*
           triangle
           triangle*
           triangle-aref
           triangle-aref*
           triangle-aref-setter
           triangle-aref-setter*
           triangle-array
           triangle-array-dimensions
           triangle-fill-pointer
           triangle-key-values
           triangle-map*
           triangle-reduce*
           triangle-setter*
           triangle-values*
           triangle-vector-push
           triangle-vector-push*
           triangle-vector-push-extend
           triangle-vector-push-extend*
           tuple-elelents
           tuple-element-type
           tuple-gensyms
           tuple-size
           tuple-typep
           tuple-typespec
           tuple-typespec*
           tuple-typespec**
           vector2d
           vector2d*
           vector2d-aref
           vector2d-aref*
           vector2d-aref-setter
           vector2d-aref-setter*
           vector2d-array
           vector2d-array-dimensions
           vector2d-component-product*
           vector2d-dot*
           vector2d-fill-pointer
           vector2d-key-values
           vector2d-length*
           vector2d-mag-square*
           vector2d-map*
           vector2d-normal*
           vector2d-reduce*
           vector2d-scale*
           vector2d-setter*
           vector2d-values*
           vector2d-vector-push
           vector2d-vector-push*
           vector2d-vector-push-extend
           vector2d-vector-push-extend*
           vector2d-vertex2d*
           vector3d
           vector3d*
           vector3d-aref
           vector3d-aref*
           vector3d-aref-setter
           vector3d-aref-setter*
           vector3d-array
           vector3d-array-dimensions
           vector3d-component-product*
           vector3d-cross*
           vector3d-difference*
           vector3d-dot*
           vector3d-fill-pointer
           vector3d-key-values
           vector3d-length*
           vector3d-mag-square*
           vector3d-map*
           vector3d-normal*
           vector3d-quaternion*
           vector3d-reduce*
           vector3d-scale*
           vector3d-setter*
           vector3d-sum*
           vector3d-values*
           vector3d-vector-push
           vector3d-vector-push*
           vector3d-vector-push-extend
           vector3d-vector-push-extend*
           vector3d-vertex3d*
           vertex2d-vector2d*
           vertex3d
           vertex3d*
           vertex3d-aref
           vertex3d-aref*
           vertex3d-aref-setter
           vertex3d-aref-setter*
           vertex3d-array
           vertex3d-array-dimensions
           vertex3d-distance*
           vertex3d-fill-pointer
           vertex3d-key-values
           vertex3d-map*
           vertex3d-reduce*
           vertex3d-setter*
           vertex3d-translation-matrix44*
           vertex3d-values*
           vertex3d-vector-push
           vertex3d-vector-push*
           vertex3d-vector-push-extend
           vertex3d-vector-push-extend*
           vertex3d-vector3d*
           width
           with-aabb
           with-aabb*
           with-aabb-aref
           with-angle-axis
           with-angle-axis*
           with-angle-axis-aref
           with-colour
           with-colour*
           with-colour-aref
           with-matrix22
           with-matrix22*
           with-matrix22-aref
           with-matrix33
           with-matrix33*
           with-matrix33-aref
           with-matrix44
           with-matrix44*
           with-matrix44-aref
           with-quaternion
           with-quaternion*
           with-quaternion-aref
           with-rect
           with-rect*
           with-rect-aref
           with-triangle
           with-triangle*
           with-triangle-aref
           with-vector2d
           with-vector2d*
           with-vector2d-aref
           with-vector3d
           with-vector3d*
           with-vector3d-aref
           with-vertex3d
           with-vertex3d*
           with-vertex3d-aref
           ))
